name: PR Preview - Publish

on:
  workflow_run:
    workflows: ["PR Preview - Build"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    permissions:
      contents: write
      pull-requests: write
    uses: adamziel/action-wp-playground-pr-preview/.github/workflows/preview-publish.yml@464a136c9f979c084d7b4e1be3aa6b2b34929403
    with:
      kind: plugin
